name: Practice Ci

on:
    push:
        branches: [main]
    workflow_dispatch: 

jobs:
    run-code:
        runs-on: ubuntu-latest

        steps:
            - name: get repo
              uses: actions/checkout@v4
            
            - name: setup node js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: install depedency 
              run: npm install

            - name: run test
              run: npm test

            - name: run code
              run: npm start


