name: Practice Ci

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    test-code:
        runs-on: ubuntu-latest

        steps:
            - name: get repo
              uses: actions/checkout@v4

            - name: setup node js
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: install dependency
              run: npm ci

            - name: run test
              run: npm test

    run-code:
        runs-on: ubuntu-latest
        needs: test-code

        steps:
            - name: get repo
              uses: actions/checkout@v4
            
            - name: setup node js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: install depedency 
              run: npm ci

            - name: run code
              run: npm start
              env:
                NODE_ENV: prod
                APP_NAME: JOY
    
    deploy-code:
      runs-on: ubuntu-latest
      needs: run-code

      steps:
        - name: doploy start
          run: echo 'start to doploing'

        - name: successfully 
          run: echo "successful"
      


